var arrLang = {
    "en-gb": {
      "HOME": "HOME", 
      "CHI_SIAMO": "WHO WE ARE",
      "PRODOTTI": "PRODUCTS",
      "CONTATTI": "CONTACTS",
      "VEA":"True Artisan Excellence",
      "SDP":"FIND OUT MORE",
      "SL":" REGISTERED OFFICE:",
      "SO":" OPERATIVE HEADQUARTERS:",
      "IT":"Italian",
      "EN":"English",

      "S0":"Who we are",
      "S1":"The history of Caffè Farnese is a story of two friends and their dream.",
      "S2":"After a long period of training and professional experience in the ho.re.ca sector, in leading companies in the world coffee market, a PASSION was nurtured.",
      "S3":"The love for the raw material, green coffee, grew every day.",
      "S4":"The dedication, research and artisanal selection have stimulated the identification of customizations of fine coffee blends, aimed at and intended for lovers of excellent tasting.",
      "S5":"A bit of history",
      "S6":"According to some historians, the origin of the coffee appears to be from the Abyssinian region of Kaffa in Ethiopia. Most likely from the etymological origin of the name, although some trace it back from the Turkish Khavè or from the Arabic Qahwa, which means stimulating.",
      "S7":"In fact, there are many legends about the origin of coffee. The best known speaks of a shepherd called Kaldi who led the goats to graze in Ethiopia. One day these, meeting a coffee plant, began to eat the berries and chew the leaves .",
      "S8":"When night came, the goats, instead of sleeping, began to wander with energy and vivacity never expressed until then. Seeing this, the shepherd identified the reason and toasted the seeds of the plant like those eaten by his flock , then he ground them and made an infusion, obtaining the coffee.",
      "S9":"In the sixteenth century with the Arab expansion, coffee spread throughout the Islamic world. In Europe and in particular in Italy it spread starting from the seventeenth century: in 1617, in fact, the first sacks of coffee beans they came to Venice via Venetian traders.",
      "S10":"At first the drink was sold in pharmacies at a high cost. But in a short time the 'coffee shops' were born, so much so that in 1763 there were 218 in Venice.",
      "S11":"Over time, coffee begins to become an opportunity for friends to meet, to chat, stay in company, experience small moments of tranquility, who used to meet in the various shops to share the unique taste of this drink." ,
      "S12":"Coffee has thus arrived in all regions of Italy, capturing its unique flavour.",
      "S13":"Composition",
      "S14":"Coffee is a drink obtained by grinding the seeds of some species of small tropical trees belonging to the genus Coffea.",
      "S15":"There are many species of plants in the genus Coffea, but only two are relevant for the production of coffee. Coffea arabica, usually known as arabica, and Coffea canephora, commonly known as Robusta. There are many of the two species variety.",
      "S16":"Processing",
      "S17":"After harvesting, the grains must be extracted from the fruit otherwise they deteriorate. There are two methods for doing this: the 'dry' and 'wet' methods.",
      "S18":"With the first method, the fruits are left in the sun and dried naturally. Subsequently they are pitted and sieved to free the grains from the pulp and peel, then they are divided by size.",
      "S19":"With the second method, the fruits are de-pulped using special machines which, in a continuous flow of water, break the skin and pulp, releasing the seeds. They are then fermented by leaving them in tanks with water for 1-3 days. Then the beans are washed and then left to dry in the sun.",
      "S20":"After drying, we proceed with pitting and sieving. The coffee thus obtained is called washed. This method requires a lot of water and is longer and more expensive, but the product obtained has a better, homogeneous and constant quality. ",
      "S21":"Toasting",
      "S22":"The roasting process is a very important and delicate moment in the manufacturing process. This process transforms the 'raw' green bean into a roasted bean, bringing out and bringing out the more than 900 essential oils contained in the bean.",
      "S23":"From our passion comes the research and selection of the best and most valuable excellences of Arabica and Robusta coffee in the world, to obtain the sublime cups of Farnese espresso that we offer to our customers.",
      "S24":"The arabica is delicate and sweet, but at the same time pleasantly acidic. Robusta is intense and decisive. Our products are Blends with balanced hints, aromas and acidity.",
      "FT1":"MT S.N.C DI TOVAGLIARI MARCO & C. - All rights reserved - ",
      "C2" : "Contact us!",
      "C3" : "Contact me!",
      "FORM0":"Fill out the form and we will contact you!",
      "FORM1":"Name and Surname",
      "FORM2":"Society",
      "FORM3":"Email address",
      "FORM4":"Telephone number",
      "FORM5":"Message",
      "FORM6":"Accept the",
      "FORM7":"Send",
      "PCASA0": "OUR PRODUCTS", 
      "PCASA1": "PROFESSIONAL LINE",
      "PCASA2": "HOME AND OFFICE LINE",
      "PCASA3": "MACHINES",
      "PCASA4": "CAPSULES & PODS",
      "PCASA5": "TRAINING COURSES",
      "PCASA6": "Discover our Training Courses",
      "SM0": "OUR BLENDS",
      "SM1": "Sweet, balanced, aromatic espresso with pleasant acidity. Notes of dark chocolate, aftertaste with a liqueur finish.",
      "SM2": "Sweet coffee with notes of liqueur and ripe fruit. Balanced acidity, velvety body, aftertaste with hints of cocoa.",
      "SM3": "Decisive, intense espresso, balanced in its syrupy aromas with notes of cocoa and hint of caramel, prolonged aftertaste with hints of toasted and biscuit.",
      "SMBUSTA": "Packaging 1 kg bag. In grains.",
      "GO_DET": "GO TO DETAILS",
      "COMPATIBILI_NESPRESSO": "NESPRESSO COMPATIBLE",
      "CIALDA_CARTA_FILTRO_38": "FILTER PAPER POD 38",
      "CIALDA_CARTA_FILTRO_44": "FILTER PAPER POD 44",
      "COMPATIBILI_A_MODO_MIO": "A MODO MIO COMPATIBLE",
      "COMPATIBILI_LAVAZZA": "LAVAZZA COMPATIBLE",
      "PBM1": "OURS MACCHINES",
      "PBM2": "POD MACHINES",
      "PBM3": "CAPSULE MACHINES",
      "PC1": "OUR CAPSULES & PODS",
      "DET": "DETAILS:",
      "FPSUB-1A": "The wine selection offered by Farnese Caffè comes to life as the 'Simone Tovagliari Wine Selection,' a result of collaboration with wine enthusiast Simone Tovagliari. Simone is a dynamic figure in the food and wine landscape, dedicated to exploring the small Champagne houses and French wineries.",
      "FPSUB-1B": "Simone Tovagliari is known for his fervent passion for wine and his commitment to discovering and promoting small producers.",
      "FPSUB-1C": "Originally from Parma, he began his journey by organizing evening events that over time evolved into authentic food and wine experiences, featuring tastings of Italian and French wines, often in collaboration with various wineries.",
      "FPSUB-2A": "His growing interest in small wineries and lesser-known producers led him to extend his exploration to France, personally visiting cellars, winemakers, and producers in the Champagne and Burgundy regions.",
      "FPSUB-2B": "Entrepreneurial and eager to learn, Simone dedicated himself to the in-depth study of the world of wine, obtaining certifications as a taster and deepening his knowledge through specialized courses.",
      "FPSUB-2C": "His mission is clear: to share his passion, enthusiasm, and acquired knowledge with friends, acquaintances, and industry professionals.",
      "FPSUB-2D": "Through constant commitment to perfection and careful product selection, Simone Tovagliari aims to import and offer authentic oenological treasures, spreading the joy of discovering and appreciating these exceptional products.",
      "FPSUB-3": "Passion, Love, Work",
      "CHISONO": "WHO I AM",
      "CORSOB": "BASIC COURSE",
      "CORSOA": "ADVANCED COURSE",
      "CORSI1":"We are proud to offer training and specialization courses in the coffee industry, custom-designed for our clients based on their level of knowledge. Our courses cover a wide range of skills, enabling anyone to learn and improve their skills in the world of coffee.",
      "CORSI2":"Starting with the basics, we offer a course that aims to provide the techniques and ways to extract a perfect espresso, as well as a practical knowledge of 'whipping' milk. This level is ideal for those who wish to acquire the basic skills needed to create the perfect cup of coffee.",
      "CORSI3":"For those interested in taking their skills to the next level, we offer advanced courses aimed at coffee professionals. These courses focus on the preparation of specialty coffees, which are authentic culinary works of art composed of tasty combinations of coffee-based elaborations. During these courses, participants will learn the advanced techniques needed to create pleasing compositions that will delight the most refined palates.",
      "CORSI4":"Join us for our training and specialization courses and discover the world of coffee in depth. Whether you are an avid beginner or an experienced barman, we have the perfect course for you. Take a break from the daily grind and immerse yourself in coffee culture with Caffè Farnese.",
      "OLPRODOTTITITLE":"My Wine Selection",
      "DESCWINE":"Wine description:",
      "NOTEDEG":"Tasting notes:",
      "ASSEMBLAGGIO":"Wine blending:",
      "TIRAGGIO":"Wine draught:",
      "DOSAGGIO":"Wine dosage:",
      "MATURAZIONE":"Wine maturation:",
      "ACCENO":"Food and wine arrangements:",
      "VINIF":"Winemaking:",
      "TEMP":"Serving Temperature:",
      "TEXTCLICK":"Click to learn more",
      "TEXTLIMIT":"Quantity available limits"

    },
    "it-it": {
      "HOME": "HOME", 
      "CHI_SIAMO": "CHI SIAMO",
      "PRODOTTI": "PRODOTTI",
      "CONTATTI": "CONTATTI",
      "VEA":"Vera Eccellenza Artigianale",
      "SDP":"SCOPRI DI PIU'",
      "SL":" SEDE LEGALE:",
      "SO":" SEDE OPERATIVA:",
      "IT":"Italiano",
      "EN":"Inglese",
      
      "S0":"Chi siamo",
      "S1":"La storia del Caffè Farnese è una storia di due amici e del loro sogno.",
      "S2":"Dopo un lungo periodo di formazione ed esperienze professionali nell’ambito ho.re.ca., in aziende leader nel mercato mondiale del caffè, si alimentava una PASSIONE.",
      "S3":"L’amore nei confronti della materia prima, il caffè verde, cresceva ogni giorno.",
      "S4":"La dedizione, la ricerca e selezione artigianale hanno stimolato l’individuazione di personalizzazioni di pregiate miscele di caffè, rivolte e destinate agli amanti della degustazione di eccellenze.",
      "S5":"Un po' di storia",
      "S6":"Secondo alcuni storici la provenienza del caffè risulta essere della regione Abissina di Kaffa in Etiopia. Molto probabilmente dall’origine etimologica del nome, anche se alcuni lo fanno risalire dal turco Khavè o dall’arabo Qahwa, che significa stimolante.",
      "S7":"Infatti esistono molte leggende sull'origine del caffè. La più conosciuta parla di un pastore chiamato Kaldi che portava a pascolare le capre in Etiopia. Un giorno queste incontrando una pianta di caffè cominciarono a mangiarne le bacche e a masticarne le foglie.",
      "S8":"Arrivata la notte, le capre, anziché dormire, si misero a vagabondare con energia e vivacità mai espressa fino ad allora. Vedendo questo, il pastore ne individuò la ragione e abbrustolì i semi della pianta come quelli mangiati dal suo gregge, poi li macinò e ne fece un'infusione, ottenendo il caffè.",
      "S9":"Nel XVI secolo con l’espansione Araba, il caffè si diffuse in tutto il mondo Islamico. In Europa e in particolare in Italia si diffuse a partire dal Seicento: nel 1617, infatti, i primi sacchi di chicchi di caffè giunsero a Venezia tramite commercianti veneziani.",
      "S10":"All’inizio la bevanda veniva venduta in farmacia ad un costo alto. Ma in poco tempo nacquero le “botteghe del caffè”, tanto che nel 1763 se ne contano ben 218 a Venezia.",
      "S11":"Con il tempo il caffè inizia a diventare l’occasione di incontro tra amici, per chiacchierare, stare in compagnia, vivere piccoli momenti di tranquillità, che si incontravano nelle diverse botteghe per condividere il gusto unico di questa bevanda.",
      "S12":"Il caffè è arrivato così in tutte le regioni di Italia catturandone il sapore unico.",
      "S13":"Composizione",
      "S14":"Il caffè è una bevanda ottenuta dalla macinazione dei semi di alcune specie di piccoli alberi tropicali appartenenti al genere Coffea.",
      "S15":"Molte sono le specie di piante del genere Coffea, ma solo due hanno rilevanza per la produzione del caffè. La Coffea arabica, detta solitamente arabica, e la Coffea canephora, nota comunemente come robusta. Delle due specie esistono poi molte varietà.",
      "S16":"Lavorazione",
      "S17":"Dopo il raccolto i chicchi vanno estratti dal frutto altrimenti si deteriorano. Per far ciò ci sono due metodi: metodo “secco” ed “umido”.",
      "S18":"Con il primo metodo, i frutti vengono lasciati al sole e fatti essiccare naturalmente. Successivamente si effettua la snocciolatura e la setacciatura per liberare i chicchi dalla polpae buccia, poi si dividono per grandezza.",
      "S19":"Con il secondo metodo, i frutti subiscono tramite apposite macchine la spolpatura che, in un flusso continuo di acqua, rompono buccia e polpa liberando i semi. Successivamente vengono fatti fermentare lasciandoli in vasche con acqua per 1-3 giorni. Di seguito i chicchi lavati e poi messi ad essiccare al sole.",
      "S20":"Terminato l’essicamento si procede alla snocciolatura e setacciatura. Il caffè cosi ottenuto si chiama lavato. Questo metodo necessita di molta acqua ed è più lungo e costoso, ma il prodotto ottenuto ha una qualità migliore, omogenee e costanti.",
      "S21":"Tostatura",
      "S22":"Il processo di tostatura è un momento molto importante e delicato della lavorazione. Questo processo trasforma il chicco verde “crudo” in chicco tostato facendo esaltare e affiorare gli oltre 900 oli essenziali contenuti nel chicco.",
      "S23":"Dalla Nostra passione nasce la ricerca e selezione delle migliori e pregiate eccellenze di caffè Arabica e Robusta al mondo, per ottenere le sublimi tazze di caffè espresso Farnese che proponiamo ai nostri clienti.",
      "S24":"L’arabica delicato e dolce, ma allo stesso tempo piacevolmente acidulo. La robusta intenso e deciso.I nostri prodotti risultano essere Blend con sentori, aromi ed acidità bilanciati.",
      "FT1":"MT S.N.C DI TOVAGLIARI MARCO & C. - Tutti i diritti sono riservati - ",
      "C2" : "Contattaci!",
      "C3" : "Contattami!",
      "FORM0":"Compila il form e ti ricontatteremo noi!",
      "FORM1":"Nome e Cognome",
      "FORM2":"Società",
      "FORM3":"Indirizzo email",
      "FORM4":"Telefono",
      "FORM5":"Messaggio",
      "FORM6":"Accetta i",
      "FORM7":"Invia",
      "PCASA0": "I NOSTRI PRODOTTI", 
      "PCASA1": "LINEA PROFESSIONALE",
      "PCASA2": "LINEA CASA & UFFICIO",
      "PCASA3": "MACCHINE",
      "PCASA4": "CAPSULE & CIALDE",
      "PCASA5": "CORSI FORMAZIONE",
      "PCASA6": "Scopri i nostri Corsi di Formazione",
      "SM0": "LE NOSTRE MISCELE",
      "SM1": "Espresso dolce, bilanciato aromatico con piacevole acidità. Note di cioccolato fondente, retrogusto con finale liquoroso.",
      "SM2": "Caffè dolce con note di liquore e frutta matura. Acidità bilanciata, corpo vellutato, retrogusto con sentori di cacao.",
      "SM3": "Espresso deciso, intenso, bilanciato nei suoi aromi sciropposi con note di cacao e punta di caramello, retrogusto prolungato con sentori di tostato e biscotto.",
      "SMBUSTA": "Confezioni busta 1 kg. In grani.",
      "GO_DET": "VAI AI DETTAGLI",
      "COMPATIBILI_NESPRESSO": "COMPATIBILI NESPRESSO",
      "CIALDA_CARTA_FILTRO_38": "CIALDA CARTA FILTRO 38",
      "CIALDA_CARTA_FILTRO_44": "CIALDA CARTA FILTRO 44",
      "COMPATIBILI_A_MODO_MIO": "COMPATIBILI A MODO MIO",
      "COMPATIBILI_LAVAZZA": "COMPATIBILI LAVAZZA",
      "PBM1": "LE NOSTRE MACCHINE",
      "PBM2": "MACCHINE PER CIALDE",
      "PBM3": "MACCHINE PER CAPSULE",
      "PC1": "LE NOSTRE CAPSULE & CIALDE",
      "DET": "DETTAGLI:",
      "FPSUB-1A": "La selezione di vini proposta da Farnese Caffè prende vita come 'Simone Tovagliari Wine Selection', frutto di una collaborazione con l'appassionato del mondo vinicolo, Simone Tovagliari. Simone è una figura intraprendente nel panorama enogastronomico, dedicato esploratore delle piccole maison dello Champagne e delle cantine francesi.",
      "FPSUB-1B": "Simone Tovagliari è noto per la sua fervente passione per il vino e il suo impegno nella scoperta e promozione di piccoli produttori.",
      "FPSUB-1C": "Originario di Parma, ha iniziato il suo percorso organizzando eventi serali che, col tempo, si sono evoluti in autentici momenti enogastronomici, tra degustazioni di vini italiani e francesi, spesso in collaborazione con diverse cantine.",
      "FPSUB-2A": "Il suo interesse crescente per le piccole cantine e produttori poco conosciuti lo ha portato a estendere la sua esplorazione fino in Francia, visitando personalmente cantine, vignaioli e produttori nelle regioni dello Champagne e della Borgogna.",
      "FPSUB-2B": "Intraprendente e desideroso di apprendere, Simone si è dedicato allo studio approfondito del mondo del vino, conseguendo certificazioni come assaggiatore e approfondendo la sua conoscenza attraverso corsi specializzati.",
      "FPSUB-2C": "La sua missione è nitida: condividere la sua passione, l'entusiasmo e la conoscenza acquisita con amici, conoscenti e professionisti del settore.",
      "FPSUB-2D": "Attraverso un impegno costante nella ricerca della perfezione e la selezione attenta dei prodotti, Simone Tovagliari si propone di importare e offrire autentici tesori enologici, diffondendo il piacere di scoprire e apprezzare questi grandi prodotti.",
      "FPSUB-3": "Passione, Amore, Lavoro",
      "CHISONO": "CHI SONO",
      "CORSOB": "CORSO BASE",
      "CORSOA": "CORSO AVANZATO",
      "CORSI1":"Siamo fieri di offrire corsi di formazione e specializzazione nel settore della caffetteria, progettati su misura per i nostri clienti in base al loro livello di conoscenza. I nostri corsi coprono una vasta gamma di competenze, consentendo a chiunque di imparare e migliorare le proprie abilità nel mondo del caffè.",
      "CORSI2":"Partendo dalle basi, offriamo un corso che mira a fornire le tecniche e le modalità per estrarre un espresso perfetto, nonché una conoscenza pratica della 'montatura' del latte. Questo livello è ideale per coloro che desiderano acquisire le competenze di base necessarie per creare una tazza di caffè perfetta.",
      "CORSI3":"Per coloro che sono interessati a portare le proprie abilità al livello successivo, offriamo corsi avanzati rivolti ai professionisti della caffetteria. Questi corsi si concentrano sulla preparazione di caffè speciali, che sono autentiche opere d'arte culinarie composte da gustose combinazioni di elaborazioni a base di caffè. Durante questi corsi, i partecipanti impareranno le tecniche avanzate necessarie per creare composizioni piacevoli che delizieranno i palati più raffinati.",
      "CORSI4":"Unisciti a noi per i nostri corsi di formazione e specializzazione e scopri il mondo del caffè in modo approfondito. Sia che tu sia un appassionato principiante o un barista esperto, abbiamo il corso perfetto per te. Prendi una pausa dal quotidiano e immergiti nella cultura del caffè con il Caffè Farnese.",
      "OLPRODOTTITITLE":"La mia selezione di Vini",
      "DESCWINE":"Descrizione del vino:",
      "NOTEDEG":"Note di degustazione:",
      "ASSEMBLAGGIO":"Assemblaggio:",
      "TIRAGGIO":"Tiraggio:",
      "DOSAGGIO":"Dosaggio:",
      "MATURAZIONE":"Maturazione:",
      "ACCENO":"Accordi enogastronomici:",
      "VINIF":"Vinificazione:",
      "TEMP":"Temperatura di servizio:",
      "TEXTCLICK":"Clicca per saperne di più",
      "TEXTLIMIT":"Quantità disponibile limitata"
    }
  };