var arrLang = {
    "en-gb": {
      "HOME": "HOME", 
      "CHI_SIAMO": "WHO WE ARE",
      "PRODOTTI": "PRODUCTS",
      "CONTATTI": "CONTACTS",
      "VEA":"True Artisan Excellence",
      "SDP":"FIND OUT MORE",
      "SL":" REGISTERED OFFICE:",
      "SO":" OPERATIVE HEADQUARTERS:",
      "IT":"Italian",
      "EN":"English",

      "S0":"Who we are",
      "S1":"The history of Caffè Farnese is a story of two friends and their dream.",
      "S2":"After a long period of training and professional experience in the ho.re.ca sector, in leading companies in the world coffee market, a PASSION was nurtured.",
      "S3":"The love for the raw material, green coffee, grew every day.",
      "S4":"The dedication, research and artisanal selection have stimulated the identification of customizations of fine coffee blends, aimed at and intended for lovers of excellent tasting.",
      "S5":"A bit of history",
      "S6":"According to some historians, the origin of the coffee appears to be from the Abyssinian region of Kaffa in Ethiopia. Most likely from the etymological origin of the name, although some trace it back from the Turkish Khavè or from the Arabic Qahwa, which means stimulating.",
      "S7":"In fact, there are many legends about the origin of coffee. The best known speaks of a shepherd called Kaldi who led the goats to graze in Ethiopia. One day these, meeting a coffee plant, began to eat the berries and chew the leaves .",
      "S8":"When night came, the goats, instead of sleeping, began to wander with energy and vivacity never expressed until then. Seeing this, the shepherd identified the reason and toasted the seeds of the plant like those eaten by his flock , then he ground them and made an infusion, obtaining the coffee.",
      "S9":"In the sixteenth century with the Arab expansion, coffee spread throughout the Islamic world. In Europe and in particular in Italy it spread starting from the seventeenth century: in 1617, in fact, the first sacks of coffee beans they came to Venice via Venetian traders.",
      "S10":"At first the drink was sold in pharmacies at a high cost. But in a short time the 'coffee shops' were born, so much so that in 1763 there were 218 in Venice.",
      "S11":"Over time, coffee begins to become an opportunity for friends to meet, to chat, stay in company, experience small moments of tranquility, who used to meet in the various shops to share the unique taste of this drink." ,
      "S12":"Coffee has thus arrived in all regions of Italy, capturing its unique flavour.",
      "S13":"Composition",
      "S14":"Coffee is a drink obtained by grinding the seeds of some species of small tropical trees belonging to the genus Coffea.",
      "S15":"There are many species of plants in the genus Coffea, but only two are relevant for the production of coffee. Coffea arabica, usually known as arabica, and Coffea canephora, commonly known as Robusta. There are many of the two species variety.",
      "S16":"Processing",
      "S17":"After harvesting, the grains must be extracted from the fruit otherwise they deteriorate. There are two methods for doing this: the 'dry' and 'wet' methods.",
      "S18":"With the first method, the fruits are left in the sun and dried naturally. Subsequently they are pitted and sieved to free the grains from the pulp and peel, then they are divided by size.",
      "S19":"With the second method, the fruits are de-pulped using special machines which, in a continuous flow of water, break the skin and pulp, releasing the seeds. They are then fermented by leaving them in tanks with water for 1-3 days. Then the beans are washed and then left to dry in the sun.",
      "S20":"After drying, we proceed with pitting and sieving. The coffee thus obtained is called washed. This method requires a lot of water and is longer and more expensive, but the product obtained has a better, homogeneous and constant quality. ",
      "S21":"Toasting",
      "S22":"The roasting process is a very important and delicate moment in the manufacturing process. This process transforms the 'raw' green bean into a roasted bean, bringing out and bringing out the more than 900 essential oils contained in the bean.",
      "S23":"From our passion comes the research and selection of the best and most valuable excellences of Arabica and Robusta coffee in the world, to obtain the sublime cups of Farnese espresso that we offer to our customers.",
      "S24":"The arabica is delicate and sweet, but at the same time pleasantly acidic. Robusta is intense and decisive. Our products are Blends with balanced hints, aromas and acidity.",
      "FT1":"MT S.N.C DI TOVAGLIARI MARCO & C. - All rights reserved - ",
      "C2" : "Contact us!",
      "C3" : "Contact me!",
      "FORM0":"Fill out the form and we will contact you!",
      "FORM1":"Name and Surname",
      "FORM2":"Society",
      "FORM3":"Email address",
      "FORM4":"Telephone number",
      "FORM5":"Message",
      "FORM6":"Accept the",
      "FORM7":"Send",
      "PCASA0": "OUR PRODUCTS", 
      "PCASA1": "PROFESSIONAL LINE",
      "PCASA2": "HOME AND OFFICE LINE",
      "PCASA3": "MACHINES",
      "PCASA4": "CAPSULES & PODS",
      "PCASA5": "TRAINING COURSES",
      "PCASA6": "Discover our Training Courses",
      "SM0": "OUR BLENDS",
      "SM1": "Sweet, balanced, aromatic espresso with pleasant acidity. Notes of dark chocolate, aftertaste with a liqueur finish.",
      "SM2": "Sweet coffee with notes of liqueur and ripe fruit. Balanced acidity, velvety body, aftertaste with hints of cocoa.",
      "SM3": "Decisive, intense espresso, balanced in its syrupy aromas with notes of cocoa and hint of caramel, prolonged aftertaste with hints of toasted and biscuit.",
      "SMBUSTA": "Packaging 1 kg bag. In grains.",
      "GO_DET": "GO TO DETAILS",
      "COMPATIBILI_NESPRESSO": "NESPRESSO COMPATIBLE",
      "CIALDA_CARTA_FILTRO_38": "FILTER PAPER POD 38",
      "CIALDA_CARTA_FILTRO_44": "FILTER PAPER POD 44",
      "COMPATIBILI_A_MODO_MIO": "A MODO MIO COMPATIBLE",
      "COMPATIBILI_LAVAZZA": "LAVAZZA COMPATIBLE",
      "PBM1": "OURS MACCHINES",
      "PBM2": "POD MACHINES",
      "PBM3": "CAPSULE MACHINES",
      "PC1": "OUR CAPSULES & PODS",
      "DET": "DETAILS:",
      "FPSUB-1A": "I am Simone Tovagliari, passionate about the world of wine, researcher of small Champagne maisons and French wineries, which thanks to my passion and dedication I started to make known and market.",
      "FPSUB-1B": "Having always had a passion for wine and good food, I have always been involved in and 'enjoyed' organizing evening events, which later turned into wine and food events in Parma's clubs and restaurants, such as tastings of Italian and later French wines, thanks also to the collaboration with several wineries. ",
      "FPSUB-1C": "This has turned my interest more and more toward this world, especially small wineries, little-known entities but highly appreciated by customers.",
      "FPSUB-2A": "The passion took hold and I became more and more interested and involved, eventually visiting wineries, winemakers and small producers in person in France, in the Champagne and Burgundy areas.",
      "FPSUB-2B": "I have had the opportunity to get closer and closer to this kind of environment, this kind of 'world', which is so wide and rich in knowledge and concepts, starting with terroirs, moving on to winemaking methods and arriving at all the various types and characteristics, about which, every day, there is always something new to learn and about which, every day, I am more and more curious to know.",
      "FPSUB-2C": "I am constantly striving to perfect my knowledge, with certified taster courses and studies in the wine industry, to lead me to personally research and select the product and then eventually import it.",
      "FPSUB-2D": "My mission? To share my passion and enjoyment of these great products with friends, acquaintances, and customers in the industry.",
      "FPSUB-3": "Passion, Love, Work",
      "CHISONO": "WHO I AM",
      "CORSOB": "BASIC COURSE",
      "CORSOA": "ADVANCED COURSE",
      "CORSI1":"We are proud to offer training and specialization courses in the coffee industry, custom-designed for our clients based on their level of knowledge. Our courses cover a wide range of skills, enabling anyone to learn and improve their skills in the world of coffee.",
      "CORSI2":"Starting with the basics, we offer a course that aims to provide the techniques and ways to extract a perfect espresso, as well as a practical knowledge of 'whipping' milk. This level is ideal for those who wish to acquire the basic skills needed to create the perfect cup of coffee.",
      "CORSI3":"For those interested in taking their skills to the next level, we offer advanced courses aimed at coffee professionals. These courses focus on the preparation of specialty coffees, which are authentic culinary works of art composed of tasty combinations of coffee-based elaborations. During these courses, participants will learn the advanced techniques needed to create pleasing compositions that will delight the most refined palates.",
      "CORSI4":"Join us for our training and specialization courses and discover the world of coffee in depth. Whether you are an avid beginner or an experienced barman, we have the perfect course for you. Take a break from the daily grind and immerse yourself in coffee culture with Caffè Farnese.",
      "OLPRODOTTITITLE":"My Wine Selection",
      "DESCWINE":"Wine description:",
      "NOTEDEG":"Tasting notes:",
      "ASSEMBLAGGIO":"Wine blending:",
      "TIRAGGIO":"Wine draught:",
      "DOSAGGIO":"Wine dosage:",
      "MATURAZIONE":"Wine maturation:",
      "ACCENO":"Food and wine arrangements:",
      "VINIF":"Winemaking:",
      "TEMP":"Serving Temperature:",

    },
    "it-it": {
      "HOME": "HOME", 
      "CHI_SIAMO": "CHI SIAMO",
      "PRODOTTI": "PRODOTTI",
      "CONTATTI": "CONTATTI",
      "VEA":"Vera Eccellenza Artigianale",
      "SDP":"SCOPRI DI PIU'",
      "SL":" SEDE LEGALE:",
      "SO":" SEDE OPERATIVA:",
      "IT":"Italiano",
      "EN":"Inglese",
      
      "S0":"Chi siamo",
      "S1":"La storia del Caffè Farnese è una storia di due amici e del loro sogno.",
      "S2":"Dopo un lungo periodo di formazione ed esperienze professionali nell’ambito ho.re.ca., in aziende leader nel mercato mondiale del caffè, si alimentava una PASSIONE.",
      "S3":"L’amore nei confronti della materia prima, il caffè verde, cresceva ogni giorno.",
      "S4":"La dedizione, la ricerca e selezione artigianale hanno stimolato l’individuazione di personalizzazioni di pregiate miscele di caffè, rivolte e destinate agli amanti della degustazione di eccellenze.",
      "S5":"Un po' di storia",
      "S6":"Secondo alcuni storici la provenienza del caffè risulta essere della regione Abissina di Kaffa in Etiopia. Molto probabilmente dall’origine etimologica del nome, anche se alcuni lo fanno risalire dal turco Khavè o dall’arabo Qahwa, che significa stimolante.",
      "S7":"Infatti esistono molte leggende sull'origine del caffè. La più conosciuta parla di un pastore chiamato Kaldi che portava a pascolare le capre in Etiopia. Un giorno queste incontrando una pianta di caffè cominciarono a mangiarne le bacche e a masticarne le foglie.",
      "S8":"Arrivata la notte, le capre, anziché dormire, si misero a vagabondare con energia e vivacità mai espressa fino ad allora. Vedendo questo, il pastore ne individuò la ragione e abbrustolì i semi della pianta come quelli mangiati dal suo gregge, poi li macinò e ne fece un'infusione, ottenendo il caffè.",
      "S9":"Nel XVI secolo con l’espansione Araba, il caffè si diffuse in tutto il mondo Islamico. In Europa e in particolare in Italia si diffuse a partire dal Seicento: nel 1617, infatti, i primi sacchi di chicchi di caffè giunsero a Venezia tramite commercianti veneziani.",
      "S10":"All’inizio la bevanda veniva venduta in farmacia ad un costo alto. Ma in poco tempo nacquero le “botteghe del caffè”, tanto che nel 1763 se ne contano ben 218 a Venezia.",
      "S11":"Con il tempo il caffè inizia a diventare l’occasione di incontro tra amici, per chiacchierare, stare in compagnia, vivere piccoli momenti di tranquillità, che si incontravano nelle diverse botteghe per condividere il gusto unico di questa bevanda.",
      "S12":"Il caffè è arrivato così in tutte le regioni di Italia catturandone il sapore unico.",
      "S13":"Composizione",
      "S14":"Il caffè è una bevanda ottenuta dalla macinazione dei semi di alcune specie di piccoli alberi tropicali appartenenti al genere Coffea.",
      "S15":"Molte sono le specie di piante del genere Coffea, ma solo due hanno rilevanza per la produzione del caffè. La Coffea arabica, detta solitamente arabica, e la Coffea canephora, nota comunemente come robusta. Delle due specie esistono poi molte varietà.",
      "S16":"Lavorazione",
      "S17":"Dopo il raccolto i chicchi vanno estratti dal frutto altrimenti si deteriorano. Per far ciò ci sono due metodi: metodo “secco” ed “umido”.",
      "S18":"Con il primo metodo, i frutti vengono lasciati al sole e fatti essiccare naturalmente. Successivamente si effettua la snocciolatura e la setacciatura per liberare i chicchi dalla polpae buccia, poi si dividono per grandezza.",
      "S19":"Con il secondo metodo, i frutti subiscono tramite apposite macchine la spolpatura che, in un flusso continuo di acqua, rompono buccia e polpa liberando i semi. Successivamente vengono fatti fermentare lasciandoli in vasche con acqua per 1-3 giorni. Di seguito i chicchi lavati e poi messi ad essiccare al sole.",
      "S20":"Terminato l’essicamento si procede alla snocciolatura e setacciatura. Il caffè cosi ottenuto si chiama lavato. Questo metodo necessita di molta acqua ed è più lungo e costoso, ma il prodotto ottenuto ha una qualità migliore, omogenee e costanti.",
      "S21":"Tostatura",
      "S22":"Il processo di tostatura è un momento molto importante e delicato della lavorazione. Questo processo trasforma il chicco verde “crudo” in chicco tostato facendo esaltare e affiorare gli oltre 900 oli essenziali contenuti nel chicco.",
      "S23":"Dalla Nostra passione nasce la ricerca e selezione delle migliori e pregiate eccellenze di caffè Arabica e Robusta al mondo, per ottenere le sublimi tazze di caffè espresso Farnese che proponiamo ai nostri clienti.",
      "S24":"L’arabica delicato e dolce, ma allo stesso tempo piacevolmente acidulo. La robusta intenso e deciso.I nostri prodotti risultano essere Blend con sentori, aromi ed acidità bilanciati.",
      "FT1":"MT S.N.C DI TOVAGLIARI MARCO & C. - Tutti i diritti sono riservati - ",
      "C2" : "Contattaci!",
      "C3" : "Contattami!",
      "FORM0":"Compila il form e ti ricontatteremo noi!",
      "FORM1":"Nome e Cognome",
      "FORM2":"Società",
      "FORM3":"Indirizzo email",
      "FORM4":"Telefono",
      "FORM5":"Messaggio",
      "FORM6":"Accetta i",
      "FORM7":"Invia",
      "PCASA0": "I NOSTRI PRODOTTI", 
      "PCASA1": "LINEA PROFESSIONALE",
      "PCASA2": "LINEA CASA & UFFICIO",
      "PCASA3": "MACCHINE",
      "PCASA4": "CAPSULE & CIALDE",
      "PCASA5": "CORSI FORMAZIONE",
      "PCASA6": "Scopri i nostri Corsi di Formazione",
      "SM0": "LE NOSTRE MISCELE",
      "SM1": "Espresso dolce, bilanciato aromatico con piacevole acidità. Note di cioccolato fondente, retrogusto con finale liquoroso.",
      "SM2": "Caffè dolce con note di liquore e frutta matura. Acidità bilanciata, corpo vellutato, retrogusto con sentori di cacao.",
      "SM3": "Espresso deciso, intenso, bilanciato nei suoi aromi sciropposi con note di cacao e punta di caramello, retrogusto prolungato con sentori di tostato e biscotto.",
      "SMBUSTA": "Confezioni busta 1 kg. In grani.",
      "GO_DET": "VAI AI DETTAGLI",
      "COMPATIBILI_NESPRESSO": "COMPATIBILI NESPRESSO",
      "CIALDA_CARTA_FILTRO_38": "CIALDA CARTA FILTRO 38",
      "CIALDA_CARTA_FILTRO_44": "CIALDA CARTA FILTRO 44",
      "COMPATIBILI_A_MODO_MIO": "COMPATIBILI A MODO MIO",
      "COMPATIBILI_LAVAZZA": "COMPATIBILI LAVAZZA",
      "PBM1": "LE NOSTRE MACCHINE",
      "PBM2": "MACCHINE PER CIALDE",
      "PBM3": "MACCHINE PER CAPSULE",
      "PC1": "LE NOSTRE CAPSULE & CIALDE",
      "DET": "DETTAGLI:",
      "FPSUB-1A": "Sono Simone Tovagliari, appassionato del mondo del vino, ricercatore di piccole maisons dello Champagne e cantine Francesi, che grazie alla mia passione e dedizione ho iniziato a far conoscere e commercializzare.",
      "FPSUB-1B": "Avendo sempre avuto la passione per il vino e il buon cibo, mi sono occupato e “divertito” di organizzare eventi serali, che si sono poi tramutati in eventi enogastronomici in locali e ristoranti di Parma, come degustazioni di vini italiani e successivamente Francesi, grazie anche alla collaborazione con diverse cantine.",
      "FPSUB-1C": "Ciò ha rivolto il mio interesse sempre più verso questo mondo, in particolare le piccole cantine, entità poco conosciute ma molto apprezzate dalla clientela.",
      "FPSUB-2A": "La passione ha preso piede e ho iniziato sempre più ad interessarmi e farmi coinvolgere, fino ad arrivare a visitare di persona cantine, vignaioli e piccoli produttori in Francia, nella zone dello Champagne e della Borgogna.",
      "FPSUB-2B": "Ho avuto la possibilità di avvicinarmi sempre più a questo tipo di ambiente, di “mondo”, così ampio e ricco di conoscenze e concetti, partendo dai Terroir, passando ai metodi di vinificazione e arrivando a tutte le varie tipologie e caratteristiche, di cui, ogni giorno, c’è sempre qualcosa di nuovo da imparare e di cui, ogni giorno, sono sempre più curioso di sapere.",
      "FPSUB-2C": "Sono alla costante ricerca di perfezionare le mie conoscenze, con corsi da assaggiatore certificato e studi nel settore vino, per portarmi a ricercare e selezionare personalmente il prodotto e per poi infine importarlo.",
      "FPSUB-2D": "La mia missione? Condividere la mia passione e il piacere per questi grandi prodotti con amici, conoscenti e clienti che operano nel settore.",
      "FPSUB-3": "Passione, Amore, Lavoro",
      "CHISONO": "CHI SONO",
      "CORSOB": "CORSO BASE",
      "CORSOA": "CORSO AVANZATO",
      "CORSI1":"Siamo fieri di offrire corsi di formazione e specializzazione nel settore della caffetteria, progettati su misura per i nostri clienti in base al loro livello di conoscenza. I nostri corsi coprono una vasta gamma di competenze, consentendo a chiunque di imparare e migliorare le proprie abilità nel mondo del caffè.",
      "CORSI2":"Partendo dalle basi, offriamo un corso che mira a fornire le tecniche e le modalità per estrarre un espresso perfetto, nonché una conoscenza pratica della 'montatura' del latte. Questo livello è ideale per coloro che desiderano acquisire le competenze di base necessarie per creare una tazza di caffè perfetta.",
      "CORSI3":"Per coloro che sono interessati a portare le proprie abilità al livello successivo, offriamo corsi avanzati rivolti ai professionisti della caffetteria. Questi corsi si concentrano sulla preparazione di caffè speciali, che sono autentiche opere d'arte culinarie composte da gustose combinazioni di elaborazioni a base di caffè. Durante questi corsi, i partecipanti impareranno le tecniche avanzate necessarie per creare composizioni piacevoli che delizieranno i palati più raffinati.",
      "CORSI4":"Unisciti a noi per i nostri corsi di formazione e specializzazione e scopri il mondo del caffè in modo approfondito. Sia che tu sia un appassionato principiante o un barista esperto, abbiamo il corso perfetto per te. Prendi una pausa dal quotidiano e immergiti nella cultura del caffè con il Caffè Farnese.",
      "OLPRODOTTITITLE":"La mia selezione di Vini",
      "DESCWINE":"Descrizione del vino:",
      "NOTEDEG":"Note di degustazione:",
      "ASSEMBLAGGIO":"Assemblaggio:",
      "TIRAGGIO":"Tiraggio:",
      "DOSAGGIO":"Dosaggio:",
      "MATURAZIONE":"Maturazione:",
      "ACCENO":"Accordi enogastronomici:",
      "VINIF":"Vinificazione:",
      "TEMP":"Temperatura di servizio:",
    }
  };